### ISSUE TITLE
CredHub Service Brokerの使い方が無理やり？

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#14]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/backend-pcc.md#credhub%E3%81%AE%E5%88%A9%E7%94%A8

ここは普通にpccサービスインスタンスをbindして、credhubは別の用途で使った方が誤解/混乱がないかと

**Comment by tkaburagi** [comment]
ですよね。。今回はCredhubはなしにしときます。
