### ISSUE TITLE
static_configの設定が不十分

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#15]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/monitoring.md#prometheus%E3%81%AB%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%81%99%E3%82%8B

api-tkaburagiしかモニタリングされていないけど、事前に全員分設定？
この見せ方だと、都度追加が必要に感じる

**Comment by tkaburagi** [comment]
事前に全員分設定しておく予定です。
