### ISSUE TITLE
UiControllerに@Controllerと@Serviceが付いている

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#19]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/deploy-ui.md#ui%E3%82%A2%E3%83%97%E3%83%AA%E3%81%AE%E9%96%8B%E7%99%BA

**Comment by tkaburagi** [comment]
不要なので削除してます。あとで反映させます。

**Comment by making** [comment]
修正コミットのメッセージに "fixes #issue番号" 入れておくと連動して便利です
