### ISSUE TITLE
org.apache.logging.log4j:log4j-to-slf4jのexcludeは必要？

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#4]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/deploy-simple-spring-boot.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E4%BD%9C%E6%88%90

**Comment by tkaburagi** [comment]
この時点では不要でした。gemfireのライブラリとコンフリクトするのでgemfire導入時に入れる必要がありそう
