### ISSUE TITLE
オンラインビルドパック？？

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#6]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/deploy-simple-spring-boot.md#%E3%83%9E%E3%83%8B%E3%83%95%E3%82%A7%E3%82%B9%E3%83%88%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4

```yaml
  buildpack: java_buildpack_offline
```

または指定なし(auto-detect)の方が良い

**Comment by tkaburagi** [comment]
おっと。直しました。
