### ISSUE TITLE
demo.sqlを設定するよりFlywayを使った方が良い

### ISSUE THREAD

**Issue by making** [tkaburagi/pcf-developer-workshop#9]
https://github.com/tkaburagi/pcf-developer-workshop/blob/master/backend-mysql.md#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E4%BF%AE%E6%AD%A3

`demo.sql`を設定する方法、productionで使わないし、設定もややこしいので、Flywayをpom.xmlに追加して、`demo.sql`を`src/main/resources/db/migration/V1__init.sql`に写した方がいい。

**Comment by tkaburagi** [comment]
口頭で補足することにします。
